service: signup-form

custom:
  tableName: ${param:table, 'signups'}-${sls:stage}

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  deploymentBucket:
    name: ${aws:accountId}-serverless-deploys
    blockPublicAccess: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:CreateTable
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 'arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.tableName}'
  environment:
    SIGNUPS_TABLE: ${self:custom.tableName}
  httpApi:
    cors: true

functions:
  api:
    handler: src/backend/handler.api
    memorySize: 128
    timeout: 15
    events:
      - httpApi: '*'
